name: Bug report
description: Create a report to help us improve KernelSU
labels: [Bug]

body:
  - type: checkboxes
    attributes:
       label: Please check before submitting an issue
       options:
          - label: I have read the documents, and haven't found anything relevant
            description: Please check [official docs](https://kernelsu.org) first
            required: true

          - label: I have searched the issues and haven't found anything relevant
            description: Search both **open** and **closed** issues before posting
            required: true

          - label: I will upload bugreport file in KernelSU Manager - Settings - Report log
            description: |
              A full `bugreport.tar.gz` is **required** for debugging kernel/root issues.
            required: true

          - label: I know how to reproduce the issue which may not be specific to my device
            description: The issue can be **stably reproduced**, not random or device-unique
            required: false

  - type: textarea
    attributes:
        label: Describe the bug
        description: A clear and concise description of what the bug is
    validations:
        required: true

  - type: textarea
    attributes:
        label: To Reproduce
        description: Steps to reproduce the behaviour
        placeholder: |
          1. Go to '...'
          2. Click on '....'
          3. See error

  - type: textarea
    attributes:
        label: Expected behavior
        description: What you expected to happen.

  - type: textarea
    attributes:
        label: Screenshots / recordings

  - type: textarea
    attributes:
        label: Logs
        description: Logcat, dmesg, crash logs, etc.

  - type: textarea
    attributes:
        label: Device info
        value: |
          - Device:
          - OS Version:
          - KernelSU Version:
          - Kernel Version:
    validations:
        required: true

  - type: textarea
    attributes:
        label: Additional context
